import Layout from '@/components/Layout'
import React from 'react'

const TermsAndConditionsScreem = () => {
  return (
    <Layout title="TEMOUS AND CONDITIONS">
        <div className="flex flex-col space-y-4 py-6 px-4 bg-white justify-center">
        <h1 className="text-xl md:text-2xl lg:text-3xl">Tech Quiz terms and conditions</h1>
        <p className="text:sm md:text-base lg:text-lg">Welcome to the terms and conditions of Tech Quiz.When accessing and using our site, you agree to comply with these terms.Read the following information carefully before continuing to use our services.</p>
        <h2 className="text-xl md:text-2xl lg:text-3xl">1. usoDoTechQuiz</h2>
        <p className="text:sm md:text-base lg:text-lg">1.1 Use Permission: We grant you a limited, non -exclusive and non -transferable license to access and use Tech Quiz strictly in accordance with these Terms and Conditions.</p>
        <p className="text:sm md:text-base lg:text-lg">1.2 Use Restrictions: You agree not to reproduce, distribute, modify, create derivative works, perform reverse engineering or commercially explore any part of Tech Quiz without our express permission in writing.</p>
        
        
        <h2 className="text-xl md:text-2xl lg:text-3xl">2. User Account</h2>
        <p className="text:sm md:text-base lg:text-lg">2.1 Account Record: To access certain features of Tech Quiz, you may need to create an account.You agree to provide accurate, complete and updated information during the registration process.</p>
        <p className="text:sm md:text-base lg:text-lg">2.2 Account Responsibility: You are responsible for maintaining the confidentiality of your account information, including password, and for all activities that occur in your account.</p>
        <h2 className="text-xl md:text-2xl lg:text-3xl">3. User Content</h2>
        <p className="text:sm md:text-base lg:text-lg">3.1 Contributions: By sending questions, answers or any other content to Tech Quiz, you give us a worldwide, non -exclusive, transferable, sublicensible, royalties license to use, reproduce, modify, distribute and display this content.</p>
        <p className="text:sm md:text-base lg:text-lg">3.2 Content Responsibility: You are entirely responsible for all the content you send.Tech Quiz does not endorse, guarantees the veracity or assumes responsibility for the content generated by users.</p>
        <h2 className="text-xl md:text-2xl lg:text-3xl">4. User conduct</h2>
        <p className="text:sm md:text-base lg:text-lg">When using Tech Quiz, you agree not to:</p>
        <p className="text:sm md:text-base lg:text-lg">4.1. Violate any applicable law or regulation.</p>
        <p className="text:sm md:text-base lg:text-lg">4.2.Send defamatory, obscene, abusive, threatening or illegal content.</p>
        <p className="text:sm md:text-base lg:text-lg">4.3. Interfere or try to interfere with the safety of Tech Quiz or related services.</p>
        <p className="text:sm md:text-base lg:text-lg">4.4. Use any device, software or routine to interfere or try to interfere with the proper operation of Tech Quiz.</p>
        <h2 className="text-xl md:text-2xl lg:text-3xl">5. Modifications and interruptions</h2>
        <p className="text:sm md:text-base lg:text-lg">We reserve the right to modify or discontinue, temporary or permanently, the Tech Quiz, with or without notice.We will not be responsible before you or third parties for any modification, suspension or interruption of services. </p>
        <h2 className = "Text-XL MD: Text-2xl LG: Text-3xl"> 6.Limitation of liability </h2>
        <p className="text:sm md:text-base lg:text-lg">Under no circumstances is tech quiz, their administrators, employees or affiliates will be responsible for any direct, indirect, incidental, special or consequent damage resulting from the use or inability to use Tech Quiz.</p>
        <h2 className="text-xl md:text-2xl lg:text-3xl">7. General provisions</h2>
        <p className="text:sm md:text-base lg:text-lg">7.1 Applicable legislation: These terms and conditions are governed and interpreted in accordance with the laws of Brazil, regardless of the conflicts of legal principles.</p>
        <p className="text:sm md:text-base lg:text-lg">7.2 Changes in the terms: We reserve the right to modify these terms and conditions at any time.Changes will take effect immediately after publication in Tech Quiz.We recommend that you regularly review the terms and conditions to be aware of any changes.</p>
        <p className="text:sm md:text-base lg:text-lg">By using Tech Quiz, you agree to comply with these terms and conditions.If you do not agree with any aspect of these terms, please stop the use of Tech Quiz.If you have questions or concerns, contact us by email devnautas.dev@gmail.com.Thanks for choosing tech quiz!</p>
       

        </div>
    </Layout>
  )
}

export default TermsAndConditionsScreem